<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head>
<title>src/java/lang/reflect/InvocationTargetException.java</title>
<meta name="robots" content="noindex,nofollow">
<meta name="generator" content="GLOBAL-6.6.3">
<meta http-equiv="Content-Style-Type" content="text/css">
<link rel="stylesheet" type="text/css" href="../style.css">
</head>
<body>
<a id="TOP" name="TOP"></a><div class="comment">
/* [&lt;][&gt;]<a href="#L97">[^]</a><a href="#L108">[v]</a>[top]<a href="#BOTTOM">[bottom]</a><a href="../mains.html">[index]</a><a href="../help.html">[help]</a> */</div>
<hr>
<h2 class="header">DEFINITIONS</h2>
This source file includes following definitions.
<ol>
<li><a href="#L97" title="Defined at 97.">getTargetException</a></li>
<li><a href="#L108" title="Defined at 108.">getCause</a></li>
</ol>
<hr>
<pre>
<div class="comment">
  Copyright (c) 1996, 2004, Oracle and/or its affiliates. All rights reserved.
  ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.</div>
<a id="L25" name="L25"></a>  25 
<a id="L26" name="L26"></a>  26 <strong class="reserved">package</strong> <a href="../S/3625.html#L43" title="Defined at 43 in src/javax/management/remote/rmi/RMIConnectionImpl_Stub.java.">java</a>.lang.reflect;
<a id="L27" name="L27"></a>  27 
<div class="comment">
  InvocationTargetException is a checked exception that wraps
  an exception thrown by an invoked method or constructor.
  <p>As of release 1.4, this exception has been retrofitted to conform to
  the general purpose exception-chaining mechanism.  The "target exception"
  that is provided at construction time and accessed via the
  {@link #getTargetException()} method is now known as the <i>cause</i>,
  and may be accessed via the {@link Throwable#getCause()} method,
  as well as the aforementioned "legacy method."
  @see Method
  @see Constructor</p></div>
<a id="L42" name="L42"></a>  42 <strong class="reserved">public</strong> <strong class="reserved">class</strong> <a href="../R/4024.html" title="Multiple referred from 140 places.">InvocationTargetException</a> <strong class="reserved">extends</strong> <a href="../S/1731.html#L35" title="Defined at 35 in src/java/lang/ReflectiveOperationException.java.">ReflectiveOperationException</a> <em class="brace">{</em>
<div class="comment">
      Use serialVersionUID from JDK 1.1.X for interoperability</div>
<a id="L46" name="L46"></a>  46     <strong class="reserved">private</strong> <strong class="reserved">static</strong> <strong class="reserved">final</strong> <strong class="reserved">long</strong> serialVersionUID = 4085088731926701167L;
<a id="L47" name="L47"></a>  47 
<div class="comment">
      This field holds the target if the
      InvocationTargetException(Throwable target) constructor was
      used to instantiate the object
      @serial</div>
<a id="L56" name="L56"></a>  56     <strong class="reserved">private</strong> <a href="../S/1726.html#L114" title="Defined at 114 in src/java/lang/Throwable.java.">Throwable</a> <a href="../D/35216.html" title="Multiple defined in 4 places.">target</a>;
<a id="L57" name="L57"></a>  57 
<div class="comment">
      Constructs an <code>InvocationTargetException</code> with
      <code>null</code> as the target exception.</div>
<a id="L62" name="L62"></a>  62     <strong class="reserved">protected</strong> InvocationTargetException() <em class="brace">{</em>
<a id="L63" name="L63"></a>  63         <strong class="reserved">super</strong>((<a href="../S/1726.html#L114" title="Defined at 114 in src/java/lang/Throwable.java.">Throwable</a>)<strong class="reserved">null</strong>);  <em class="comment">// Disallow initCause</em>
<a id="L64" name="L64"></a>  64     <em class="brace">}</em>
<a id="L65" name="L65"></a>  65 
<div class="comment">
      Constructs a InvocationTargetException with a target exception.
      @param target the target exception</div>
<a id="L71" name="L71"></a>  71     <strong class="reserved">public</strong> InvocationTargetException(<a href="../S/1726.html#L114" title="Defined at 114 in src/java/lang/Throwable.java.">Throwable</a> <a href="../D/35216.html" title="Multiple defined in 4 places.">target</a>) <em class="brace">{</em>
<a id="L72" name="L72"></a>  72         <strong class="reserved">super</strong>((<a href="../S/1726.html#L114" title="Defined at 114 in src/java/lang/Throwable.java.">Throwable</a>)<strong class="reserved">null</strong>);  <em class="comment">// Disallow initCause</em>
<a id="L73" name="L73"></a>  73         <strong class="reserved">this</strong>.<a href="../D/35216.html" title="Multiple defined in 4 places.">target</a> = <a href="../D/35216.html" title="Multiple defined in 4 places.">target</a>;
<a id="L74" name="L74"></a>  74     <em class="brace">}</em>
<a id="L75" name="L75"></a>  75 
<div class="comment">
      Constructs a InvocationTargetException with a target exception
      and a detail message.
      @param target the target exception
      @param s      the detail message</div>
<a id="L83" name="L83"></a>  83     <strong class="reserved">public</strong> InvocationTargetException(<a href="../S/1726.html#L114" title="Defined at 114 in src/java/lang/Throwable.java.">Throwable</a> <a href="../D/35216.html" title="Multiple defined in 4 places.">target</a>, <a href="../D/8419.html" title="Multiple defined in 2 places.">String</a> s) <em class="brace">{</em>
<a id="L84" name="L84"></a>  84         <strong class="reserved">super</strong>(s, <strong class="reserved">null</strong>);  <em class="comment">// Disallow initCause</em>
<a id="L85" name="L85"></a>  85         <strong class="reserved">this</strong>.<a href="../D/35216.html" title="Multiple defined in 4 places.">target</a> = <a href="../D/35216.html" title="Multiple defined in 4 places.">target</a>;
<a id="L86" name="L86"></a>  86     <em class="brace">}</em>
<a id="L87" name="L87"></a>  87 
<div class="comment">
      Get the thrown target exception.
      <p>This method predates the general-purpose exception chaining facility.
      The {@link Throwable#getCause()} method is now the preferred means of
      obtaining this information.
      @return the thrown target exception (cause of this exception).</p></div>
<a id="L97" name="L97"></a>  97     <strong class="reserved">public</strong> <a href="../S/1726.html#L114" title="Defined at 114 in src/java/lang/Throwable.java.">Throwable</a> <a href="../R/19397.html" title="Multiple referred from 44 places.">getTargetException</a>() <em class="brace">{</em>
<a id="L98" name="L98"></a>  98         <strong class="reserved">return</strong> <a href="../D/35216.html" title="Multiple defined in 4 places.">target</a>;
<a id="L99" name="L99"></a>  99     <em class="brace">}</em>
<a id="L100" name="L100"></a> 100 
<div class="comment">
      Returns the cause of this exception (the thrown target exception,
      which may be <code>null</code>).
      @return  the cause of this exception.
      @since   1.4</div>
<a id="L108" name="L108"></a> 108     <strong class="reserved">public</strong> <a href="../S/1726.html#L114" title="Defined at 114 in src/java/lang/Throwable.java.">Throwable</a> <a href="../R/15467.html" title="Multiple referred from 93 places.">getCause</a>() <em class="brace">{</em>
<a id="L109" name="L109"></a> 109         <strong class="reserved">return</strong> <a href="../D/35216.html" title="Multiple defined in 4 places.">target</a>;
<a id="L110" name="L110"></a> 110     <em class="brace">}</em>
<a id="L111" name="L111"></a> 111 <em class="brace">}</em>
</pre>
<hr>
<div class="comment">
/* [&lt;][&gt;]<a href="#L97">[^]</a><a href="#L108">[v]</a><a href="#TOP">[top]</a>[bottom]<a href="../mains.html">[index]</a><a href="../help.html">[help]</a> */</div>
</body></html>